name: Mirror to Personal Repo for Deployment

on:
  push:
    branches:
      - main

jobs:
  mirror:
    if: github.repository == 'GDSC-OregonState/GDGC-Club-Website'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:purelyKai/GDGC-Club-Website-Mirror.git
          ssh_private_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
